sudo: required
services:
  - docker

before_install:
  - docker build -t erozeuya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true erozeuya/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-992382435296"
  pucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key: "$AWS_SECRET_KEY"
